# DB

spring:
  config:
    activate:
      on-profile: staging
  
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create