# DB

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/local
    username: sa
    userpassword:
    driver-class-name: org.h2.Driver
      
      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update

  data:
    redis:
      host: "localhost"
      port: 6379
