# DB

spring:
  profiles:
    active: local
  
  message:
    basename: errors

  mail:
    host: smtp.gmail.com
    port: 587
    username: smusoak@gmail.com
    password: daiz jwwm okyi bupk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-milis: 1800000
