# DB

spring:
  config:
    activate:
      on-profile: local
      
  datasource:
    url: jdbc:h2:~/local
    username: sa
    userpassword:
    driver-class-name: org.h2.Driver	
      
      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update