# DB

spring:
  config:
    activate:
      on-profile: staging
  
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    auth-code-expirationms: ${MAIL_EXPIRATION}

token:
  secret:
    # Generate by
    # node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
    key: ${TOKEN_SECRET_KEY}
  # 1hour
  expirationms: ${TOKEN_EXPIRATION}

admin:
  mail: ${ADMIN_MAIL}
  password: ${ADMIN_PASSWORD}
